### PR TITLE
Review: Theory & Methods

### LINKED ISSUE #242: Review: Theory & Methods

### PR DESCRIPTION
**Pull request by Kechr**

### CODE REVIEW

**Comment by Joergenson** [comment]
line 35: "revolves around" the world around the world around 
line 56: To acquire data points instead perhaps?
line 74: Awkward cite 
line 99: The reader have a chance of not knowing what we mean by iterations
line 160:  Capital letters at the start of the sentences

**Comment by Kechr** [comment]
L032: Rewrite this sentence.
L035: "... evolves ..." -> "... revolves ..."
L041: Consider de-bolding the letters 'O', 'E', and 'E', as this is the only time in the report this is used.
L064: Fix spacing
L074: cite should be placed before new line
L108: Consider rewording. ('answer' is the culprit here)
L114: Remove unnecessary comma after project (?)
L115: Oxford comma
L122: tasks -> issues
L128: task -> issue
L131: decided to use an -> decided on an
L136: Not in ZenHub, but on ZenHub
L140: Caption -> Scrum board or kanban board?
L152: Prioritising model -> prioritisation technique 
L155: Comma before as
L160: All sentences should start with a capitalised letter in the description.
L203: Capitalise 'i' in 'is'

**Comment by kkmp-dk** [comment]
L082 shot -> short ?

**Comment by Bokaiii** [comment]
- “To be sure to understand” = “To ensure an understanding of”
- 2.1.1 Automation Pyramid
    - "Combines the previous level" = "combines the previous levels" (plural)
    - On this level, the ERP….. = On this level, the management system ERP,…
- 2.1.3 Optimal Production Speed
    - Move citation ([3])
- 2.2.4 FURPS+
    - Help giving = helps give (beginning)

**Pull request merged**
