### PR TITLE
Review: Architecture

### LINKED ISSUE #245: Review: Architecture

### PR DESCRIPTION
**Pull request by Kechr**

### CODE REVIEW

**Comment by Joergenson** [comment]
line 6: ., needs fix
line 33: Slight chance we might need to add a copy of this to the appendix.

**Comment by Kechr** [comment]
L35: width=1\textwidth

**Comment by Bokaiii** [comment]
Architecture:
- Present tense

**Comment by nymann** [comment]
> A web client is a more simple solution

I don't agree with this. It's a better solution since it's more dynamic, we shouldn't downplay ourselves.

**Comment by nymann** [comment]
> ... batch to generate a batch report

Is the name batch report still relevant?

**Pull request merged**
